### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by kvz** [transloadit/python-sdk#10]
:wave: Hi there, Ife left Transloadit and we're looking for someone to maintain this Python SDK. One often heard feature request is:

- Adding Asyncio support #9 

So before deciding, you could already ponder about if this is to your liking.

Shoot me an email or tweet if you are interested, it would be a paid thing and only require a few hours here and there.

/cc @arnaudlimbourg something for you maybe?

**Comment by arnaudlimbourg** [comment]
@kvz I'm not sure what the asyncio support would look like. Using httpx we could achieve some async aspects for the http requests but I have trouble imagining what it could be :)

**Comment by kvz** [comment]
@ifedapoolarewaju perhaps you can share your ideas on this one so Arnaud can have a better mental picture?

**Comment by ifedapoolarewaju** [comment]
what I had in mind from my experience with using other SDKs is to have a parallel API to the current synchronous version. So we could have both:

```
tl = client.Transloadit(...)
tl_async = client.AsyncTransloadit(...)
```

meaning all the methods that would've been synchronous with `tl` will now be async with `tl_async`. Something similar is done with the [elasticsearch python sdk](https://elasticsearch-py.readthedocs.io/en/v7.11.0/async.html)

**Comment by kvz** [comment]
I'm very unfamiliar with the python ecosystem--is there a good reason to want the sync behavior other than BC? Like, is the entire ecosystem moving towards async? If so, a new SemVer Major that just offers the async way, might be preferable over offering both interfaces. But I'm not in a position to make a good judgement call there

**Comment by arnaudlimbourg** [comment]
> what I had in mind from my experience with using other SDKs is to have a parallel API to the current synchronous version. So we could have both:
> 

I see, I'll have a look at the elastic search one, thanks!



> I'm very unfamiliar with the python ecosystem--is there a good reason to want the sync behavior other than BC? Like, is the entire ecosystem moving towards async? If so, a new SemVer Major that just offers the async way, might be preferable over offering both interfaces. But I'm not in a position to make a good judgement call there

Nope, there is more support but you should not have just an async api. Sync is still the most common as far as I know.

**Comment by ifedapoolarewaju** [comment]
Yes, what @arnaudlimbourg said. The sync and async APIs are sort of like two parallel architectures, so a project with sync codebase will most likely find it easier to integrate the sync API, while a project with async codebase will equally drool over the async API.

**Comment by kvz** [comment]
:tada: @arnaudlimbourg was installed as the Python SDKs new lead.
