### ISSUE TITLE
Requests time out when sent from the Python SDK

### ISSUE THREAD

**Issue by Missing-Tech** [transloadit/python-sdk#13]
It's only an issue when creating assemblies with the Python SDK, even if they're the first assemblies I've made that day.

Error message that gets displayed:
```
{'error': 'RATE_LIMIT_REACHED', 'message': 'Request limit reached', 'http_code': 429, 'info': {'retryIn': 0}}
```

Video showcasing the issue:
https://user-images.githubusercontent.com/36996165/171034785-903f6308-b320-4fbd-bd36-3ee1d231e2e6.mp4

Python Code to replicate:
```python
# pip install pytransloadit
from transloadit import client

tl = client.Transloadit('AUTH_KEY', 'AUTH_SECRET')
assembly = tl.new_assembly()

# Set Encoding Instructions
assembly.add_step(':original', '/upload/handle', {})
assembly.add_step('resized', '/image/resize', {
  'use': ':original',
  'result': True,
  'height': 500,
  'imagemagick_stack': 'v2.0.7',
  'resize_strategy': 'fit',
  'width': 500,
  'zoom': False
})

# Add files to upload
assembly.add_file(open('demo.jpg', 'rb'))

# Start the Assembly
assembly_response = assembly.create(retries=0, wait=True)

print(assembly_response.data)
```

**Comment by Missing-Tech** [comment]
Could you take a look please @arnaudlimbourg? We've had a few customers report this recently

**Comment by kvz** [comment]
Could it be that the python code requests a status many more times than other SDKs? We did make our rate limiter more capable recently, perhaps that reveals that the python sdk should be waiting a little longer between polling? Just a hunch
