### ISSUE TITLE
The latest release requires pypandoc, which requires pandoc to be installed

### ISSUE THREAD

**Issue by espenak** [transloadit/python-sdk#2]
This is caused by ``import pypandoc``, and the use of ``pypandoc`` in ``setup.py``.

This is a huge issue with server installs since it requires pandoc to be available on the server. It is also very much a strange thing to require developers to have available on their development machines just to use the library (since long_description is only used to generate the pypi pages).

If you really need to use pypandoc in setup.py, could you at least use something like this?:

```python
try:
    import pypandoc
except ImportError:
    pypandoc_available = False
else:
    pypandoc_available = True

# ...

if pypandoc_available:
     long_description = pypandoc.convert('README.md', 'rst')
     long_description = long_description.replace("\r","")
else:
     try:
          long_description = open('README.md', 'r).read()
     except IOError:
          long_description = ''
```

## Simpler and less error prone alternatives:
- use a ``README.rst`` instead of a ``README.md``, and not require pypandoc at all.
- use a long_description that just say that the docs are available at https://transloadit.readthedocs.io/.

**Comment by ifedapoolarewaju** [comment]
@espenak Sorry it took a bit of time to respond, I must have missed this in notifications. I have added and [released a fix](https://github.com/transloadit/python-sdk/releases/tag/v0.1.4) for this. Please let me know if you still have any issues with this. 🙂 

Thank you for reporting.
