### ISSUE TITLE
Add python 3.12 support

### ISSUE THREAD

**Issue by Artui** [transloadit/python-sdk#28]
Hello,

I was looking to update my project that uses this library to Python 3.12, but this version is blocked in the `pyproject.toml`:
```
[tool.poetry.dependencies]
python = ">=3.7,<3.12"
```

If it's possible, can the version be bumped to `<3.13`?

Thanks!

**Comment by Artui** [comment]
Just FYI - I've cloned the repo and have a branch locally with all the needed changes for this update, and everything seems to work fine, the tests pass, and no dependencies seem to complain regarding version compatibility.

**Comment by kvz** [comment]
Would you like to push this work so you can PR it? Then we can also see if CI agrees

**Comment by Artui** [comment]
@kvz yes, I'd be happy to! To be honest, I've never pushed into public repos before, so I don't know what's needed there. Do you need to add me as a contributor? :D

**Comment by kvz** [comment]
Since this is open source you can first fork the repo under your own account. then clone that. Then apply the commits. You can then open a PR based on your fork 👌 

Let me know if it works out and thank you for your time already ❤️

**Comment by Artui** [comment]
@kvz thank you for these pointers! It's very helpful :)

**Comment by Artui** [comment]
I see that we cannot update to 3.12 without dropping support for 3.7. @kvz is it a viable option, to release a new version that drops support for 3.7, but adds support for 3.12?

**Comment by kvz** [comment]
We can cut a major release, but for that we should summon the maintainers for sure (I’m just casually driving by as a node dev :). Left some mentions in the PR 👌

Thank you for your work and bearing with us! 💪💪

**Comment by cdr-chakotay** [comment]
This has been shipped. Thank you again @Artui :)
