### ISSUE TITLE
Loosen requests version requirement

### ISSUE THREAD

**Issue by arnaudlimbourg** [transloadit/python-sdk#5]
Hello,

In the current ``setup.py`` the version for ``requests`` is locked to ``2.11.1``, is it possible to make the requirement as < 3 and > 2.11 ?

Using ``pipenv`` it is not possible to install this package if a higher version of ``requests`` is already present.

Thanks!

**Comment by ifedapoolarewaju** [comment]
@arnaudlimbourg done! https://github.com/transloadit/python-sdk/releases/tag/v0.1.9
